apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  template:
    metadata:
      name: nginx
  spec:
    containers:
    - name: nginx
      image: registry-jpe2.r-local.net/cpd-support-marvel/nginx:latest
      ports:
      - containerPort: 80
